/*
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import org.openapitools.client.ApiException;
import org.openapitools.client.model.PageWrapperAssetDto;
import org.openapitools.client.model.PageWrapperMarketVenueDto;
import org.openapitools.client.model.PageWrapperObMarketDto;
import org.openapitools.client.model.PageWrapperObPairDto;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for DataDictionariesOrderBooksApi
 */
@Disabled
public class DataDictionariesOrderBooksApiTest {

    private final DataDictionariesOrderBooksApi api = new DataDictionariesOrderBooksApi();

    /**
     * Get assets
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void orderBookAssetsTest() throws ApiException {
        Integer page = null;
        Integer size = null;
        PageWrapperAssetDto response = api.orderBookAssets(page, size);
        // TODO: test validations
    }

    /**
     * Get market-venues
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void orderBookMarketVenuesTest() throws ApiException {
        Boolean active = null;
        Integer page = null;
        Integer size = null;
        PageWrapperMarketVenueDto response = api.orderBookMarketVenues(active, page, size);
        // TODO: test validations
    }

    /**
     * Get markets
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void orderBookMarketsTest() throws ApiException {
        Boolean active = null;
        String symbol = null;
        String base = null;
        String assetType = null;
        String marketVenue = null;
        String pairId = null;
        Boolean verbose = null;
        Integer page = null;
        Integer size = null;
        PageWrapperObMarketDto response = api.orderBookMarkets(active, symbol, base, assetType, marketVenue, pairId, verbose, page, size);
        // TODO: test validations
    }

    /**
     * Get pairs
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void orderBookPairsTest() throws ApiException {
        Boolean active = null;
        String symbol = null;
        String base = null;
        String assetType = null;
        Integer page = null;
        Integer size = null;
        PageWrapperObPairDto response = api.orderBookPairs(active, symbol, base, assetType, page, size);
        // TODO: test validations
    }

}
