/*
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for BestOfferDto
 */
public class BestOfferDtoTest {
    private final BestOfferDto model = new BestOfferDto();

    /**
     * Model tests for BestOfferDto
     */
    @Test
    public void testBestOfferDto() {
        // TODO: test BestOfferDto
    }

    /**
     * Test the property 'changes'
     */
    @Test
    public void changesTest() {
        // TODO: test changes
    }

    /**
     * Test the property 'open'
     */
    @Test
    public void openTest() {
        // TODO: test open
    }

    /**
     * Test the property 'high'
     */
    @Test
    public void highTest() {
        // TODO: test high
    }

    /**
     * Test the property 'low'
     */
    @Test
    public void lowTest() {
        // TODO: test low
    }

    /**
     * Test the property 'close'
     */
    @Test
    public void closeTest() {
        // TODO: test close
    }

}
