/*
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.openapitools.client.model.PairDto;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for MarketDto
 */
public class MarketDtoTest {
    private final MarketDto model = new MarketDto();

    /**
     * Model tests for MarketDto
     */
    @Test
    public void testMarketDto() {
        // TODO: test MarketDto
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'marketVenue'
     */
    @Test
    public void marketVenueTest() {
        // TODO: test marketVenue
    }

    /**
     * Test the property 'pairId'
     */
    @Test
    public void pairIdTest() {
        // TODO: test pairId
    }

    /**
     * Test the property 'pair'
     */
    @Test
    public void pairTest() {
        // TODO: test pair
    }

}
