/*
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.openapitools.client.model.BestOfferDto;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for ObMetricsDto
 */
public class ObMetricsDtoTest {
    private final ObMetricsDto model = new ObMetricsDto();

    /**
     * Model tests for ObMetricsDto
     */
    @Test
    public void testObMetricsDto() {
        // TODO: test ObMetricsDto
    }

    /**
     * Test the property 'bestAsk'
     */
    @Test
    public void bestAskTest() {
        // TODO: test bestAsk
    }

    /**
     * Test the property 'bestBid'
     */
    @Test
    public void bestBidTest() {
        // TODO: test bestBid
    }

    /**
     * Test the property 'vwmp'
     */
    @Test
    public void vwmpTest() {
        // TODO: test vwmp
    }

}
