/*
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for PairDto
 */
public class PairDtoTest {
    private final PairDto model = new PairDto();

    /**
     * Model tests for PairDto
     */
    @Test
    public void testPairDto() {
        // TODO: test PairDto
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'assetType'
     */
    @Test
    public void assetTypeTest() {
        // TODO: test assetType
    }

    /**
     * Test the property 'symbol'
     */
    @Test
    public void symbolTest() {
        // TODO: test symbol
    }

    /**
     * Test the property 'base'
     */
    @Test
    public void baseTest() {
        // TODO: test base
    }

    /**
     * Test the property 'futureDeliveryDate'
     */
    @Test
    public void futureDeliveryDateTest() {
        // TODO: test futureDeliveryDate
    }

    /**
     * Test the property 'optionType'
     */
    @Test
    public void optionTypeTest() {
        // TODO: test optionType
    }

    /**
     * Test the property 'optionExpiration'
     */
    @Test
    public void optionExpirationTest() {
        // TODO: test optionExpiration
    }

    /**
     * Test the property 'optionStrike'
     */
    @Test
    public void optionStrikeTest() {
        // TODO: test optionStrike
    }

    /**
     * Test the property 'optionDeliveryDate'
     */
    @Test
    public void optionDeliveryDateTest() {
        // TODO: test optionDeliveryDate
    }

}
