/*
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for TradeMetricsDto
 */
public class TradeMetricsDtoTest {
    private final TradeMetricsDto model = new TradeMetricsDto();

    /**
     * Model tests for TradeMetricsDto
     */
    @Test
    public void testTradeMetricsDto() {
        // TODO: test TradeMetricsDto
    }

    /**
     * Test the property 'price'
     */
    @Test
    public void priceTest() {
        // TODO: test price
    }

    /**
     * Test the property 'volume'
     */
    @Test
    public void volumeTest() {
        // TODO: test volume
    }

    /**
     * Test the property 'trades'
     */
    @Test
    public void tradesTest() {
        // TODO: test trades
    }

    /**
     * Test the property 'vwap'
     */
    @Test
    public void vwapTest() {
        // TODO: test vwap
    }

}
